import{a as h,S as b,i as s}from"./assets/vendor-DqSH9NcY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const L="https://pixabay.com/api/",S="47343859-71412f3a0c5519c6640fc8f75";function q(a,t=1,o=20){return h.get(L,{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:o}})}let c;function P(a){const t=document.querySelector(".gallery"),o=a.map(({webformatURL:n,LargeImageURL:e,tags:r,likes:i,views:g,comments:p,downloads:y})=>`
        <a href="${largeImageURL}" class="gallery__item">          
            <img src="${n}" alt="${r}" loading="lazy" class="image-card__img"/>            
              <p><b>Likes:</b> ${i}</p>
              <p><b>Views:</b> ${g}</p>
              <p><b>Comments:</b> ${p}</p>
              <p><b>Downloads:</b> ${y}</p>                     
        </a>
        `).join("");t.innerHTML=o,c?c.refresh():c=new b(".gallery a")}function _(){const a=document.querySelector(".gallery");a.innerHTML=""}const f=document.querySelector("#search-form"),$=f.querySelector("input");document.querySelector(".gallery");const d=document.querySelector(".loader");let l=1,u="";const w=20;f.addEventListener("submit",E);function E(a){a.preventDefault();const t=$.value.trim();if(!t){s.warning({title:"Warning",message:"Search query cannot be empty."});return}u=t,l=1,_(),I(),q(u,l,w).then(o=>{m();const n=o.data;if(n.hits.length===0){s.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again."});return}P(n.hits)}).catch(o=>{m(),s.error({title:"Error",message:"Failed to load images. Please try again later."}),console.error("Error fetching images:",o)})}function I(){d.style.display="block"}function m(){d.style.display="none"}
//# sourceMappingURL=index.js.map
